# Generated by Django 2.2.3 on 2019-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emaile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email_name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
            ],
        ),
    ]
