# Generated by Django 2.2.3 on 2019-07-30 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bryopo', '0002_auto_20190729_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oposy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opo_name', models.CharField(max_length=200, verbose_name='opo_name')),
                ('opo_title', models.CharField(max_length=200, verbose_name='opo_name')),
                ('opo_cat', models.CharField(max_length=100, verbose_name='opo_category')),
                ('opo_cat_name', models.CharField(max_length=100, verbose_name='opo_category_name')),
                ('opo_text', models.TextField(verbose_name='opo_text')),
                ('year_added', models.CharField(max_length=4, verbose_name='year_added')),
            ],
        ),
        migrations.AlterField(
            model_name='emaile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 13, 37, 38, 559396, tzinfo=utc), verbose_name='created_date'),
        ),
    ]
